import { IHeroesDTO } from '@/types';

export const responseCharacterData = {
  id: 1,
  name: 'Sample Character',
  height: '175',
  mass: '70',
  hair_color: 'red',
  skin_color: 'tan',
  eye_color: 'green',
  birth_year: '20BBY',
  gender: 'female',
  homeworld: 2,
  films: [2, 3, 4, 5],
  species: [2],
  vehicles: [15, 31],
  starships: [22, 33],
  created: '2015-01-10T14:00:00.000Z',
  edited: '2015-01-15T15:00:00.000Z',
  url: 'https://sw-api.starnavi.io/people/1/',
};

export const mockMovies = [
  {
    id: 1,
    title: 'Movie 1',
    episode_id: 1,
    opening_crawl: 'Movie_test_1',
    director: 'Director_1',
    producer: 'Producer A',
    release_date: '2006-06-10',
    characters: [20],
    planets: [2],
    starships: [58],
    vehicles: [60],
    species: [25],
    created: '2015-01-15T19:00:00.000Z',
    edited: '2015-01-15T21:00:00.000Z',
    url: 'https://sw-api.starnavi.io/films/1/',
  },
  {
    id: 2,
    title: 'Movie 2',
    episode_id: 2,
    opening_crawl: 'Movie_test_2',
    director: 'Director_2',
    producer: 'Producer B',
    release_date: '2006-06-10',
    characters: [20],
    planets: [2],
    starships: [58],
    vehicles: [60],
    species: [25],
    created: '2015-01-15T19:00:00.000Z',
    edited: '2015-01-15T21:00:00.000Z',
    url: 'https://sw-api.starnavi.io/films/2/',
  },
];

export const mockSpaceCraft = [
  {
    id: 58,
    name: 'Galactic Cruiser',
    model: 'Model-X',
    manufacturer: 'Galactic Enterprises',
    cost_in_credits: '200000',
    length: '10',
    max_atmosphering_speed: '1200',
    crew: '2',
    passengers: '0',
    cargo_capacity: '80',
    consumables: '10 days',
    hyperdrive_rating: '0.5',
    MGLT: 'unknown',
    starship_class: 'Cruiser',
    pilots: [20, 60],
    films: [6, 7],
    created: '2015-01-15T17:35:23.906Z',
    edited: '2015-01-15T21:23:49.930Z',
    url: 'https://sw-api.starnavi.io/starships/58/',
  },
];

export const mockCharacters: IHeroesDTO = {
  count: 3,
  next: '',
  previous: '',
  results: [
    {
      id: 1,
      name: 'Character One',
      height: '185',
      mass: '90',
      hair_color: 'brown',
      skin_color: 'fair',
      eye_color: 'blue',
      birth_year: '1992',
      gender: 'male',
      homeworld: 1,
      films: [],
      species: [],
      vehicles: [],
      starships: [],
      created: '',
      edited: '',
      url: '',
    },
    {
      id: 2,
      name: 'Character Two',
      height: '165',
      mass: '65',
      hair_color: 'blonde',
      skin_color: 'light',
      eye_color: 'brown',
      birth_year: '1988',
      gender: 'female',
      homeworld: 3,
      films: [],
      species: [],
      vehicles: [],
      starships: [],
      created: '',
      edited: '',
      url: '',
    },
    {
      id: 3,
      name: 'Character Three',
      height: '170',
      mass: '75',
      hair_color: 'black',
      skin_color: 'dark',
      eye_color: 'grey',
      birth_year: '1995',
      gender: 'other',
      homeworld: 4,
      films: [],
      species: [],
      vehicles: [],
      starships: [],
      created: '',
      edited: '',
      url: '',
    },
  ],
};
